SRC_DIRS += vendor/logger/src vendor/simpleFiles/src vendor/simpleSockets/src
INCLUDE_DIR +=  vendor/logger/include vendor/simpleErrorCheck/include vendor/simpleFiles/include vendor/simpleSockets/include
