

$(PCH_OUT): $(PCH_PATH)
	@echo "building pch" 
	@echo $(MAKECMDGOALS) $(PCH_OUT)
	$(CXX) -c $(INC_FLAGS) $(CPPFLAGS) $(CXXFLAGS) -o $(PCH_OUT) $(PCH_PATH)


ifneq (./$(MAKECMDGOALS),$(PCH_OUT))
# CPPFLAGS += -include-pch $(PCH_OUT) 
endif
