
# c++ source
$(BUILD_DIR)/%.o: %.cpp
	@echo "building file: " $< " with id " $(call getFileId,$<)
	$(MKDIR_P) $(dir $@)
	$(CC)  $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@


#c source
$(BUILD_DIR)/%.o: %.c
	@echo "building file: " $< " with id " $(call getFileId,$<) 
	$(MKDIR_P) $(dir $@)
	$(CC)  $(CFLAGS) $(CXXFLAGS)  -c $< -o $@



